### ISSUE TITLE
If condition in badge function (on the "main" branch)

### ISSUE THREAD

**Issue by VincentBellavance** [ReseauBiodiversiteQuebec/mapselector#4]
Seems like there is a small error in the badge function on the main branch. The condition should be if(use_badge) instead of if(badge). I think you changed it in the "better-modalData" branch, but it's just to make sure that the error don't stay there!

**Comment by aammd** [comment]
gah, oops! well this should disappear when we merge #3

**Comment by VincentBellavance** [comment]
Perfect!

**Comment by aammd** [comment]
should be good now!
